image: node:latest

stages:
  - build
  - lint
  - test
  - deploy

# Cache npm modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - Lab_Assistant/lambda/custom/node_modules/

before_script:
  - cd Lab_Assistant/lambda/custom
  - npm install

build:
  stage: build
  script:
    - npm run build
  except:
    - deploy@nfriend/lab-assistant

lint code:
  stage: lint
  script:
    - npm run lint
  except:
    - deploy@nfriend/lab-assistant

lint translations:
  stage: lint
  script:
    - ./ci-scripts/check-for-new-translations.sh
  except:
    - deploy@nfriend/lab-assistant

jest:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - Lab_Assistant/lambda/custom/test-report.xml
    reports:
      junit: Lab_Assistant/lambda/custom/test-report.xml
  except:
    - deploy@nfriend/lab-assistant

deploy:
  stage: deploy
  script:
    - npm install -g ask-cli
    - ./ci-scripts/create-ask-cli-config.js
    - npm run deploy
  only:
    - deploy@nfriend/lab-assistant
