image: node:latest

stages:
  - build
  - lint
  - test
  - deploy

# Cache npm modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - Lab_Assistant/lambda/custom/node_modules/

before_script:
  - cd Lab_Assistant/lambda/custom
  - npm install

build:
  stage: build
  script:
    - npm run build

lint code:
  stage: lint
  script:
    - npm run lint

lint translations:
  stage: lint
  script:
    - npm run build-and-translate
    - git diff-index --quiet HEAD -- ||
      (
      echo "New text has been added! Please run \"npm run translate\" and commit these changes." &&
      exit 1
      )

jest:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - Lab_Assistant/lambda/custom/test-report.xml
    reports:
      junit: Lab_Assistant/lambda/custom/test-report.xml

deploy:
  stage: deploy
  script:
    - npm run deploy
  only:
    - deploy@nfriend/lab-assistant
