image: node:latest

stages:
  - build
  - lint
  - test
  - deploy
  - demo

# Cache npm modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - Lab_Assistant/lambda/custom/node_modules/

before_script:
  - cd Lab_Assistant/lambda/custom
  - npm install

.except-default: &except-default
  except:
    variables:
      - $LAB_ASSISTANT

build:
  <<: *except-default
  stage: build
  script:
    - npm run build

lint code:
  <<: *except-default
  stage: lint
  script:
    - npm run lint

lint translations:
  <<: *except-default
  stage: lint
  script:
    - ./ci-scripts/check-for-new-translations.sh

lint model:
  <<: *except-default
  image: nathanfriend/java-node-git:latest
  stage: lint
  script:
    - ./ci-scripts/check-for-model-changes.sh

jest:
  <<: *except-default
  stage: test
  needs: ['build']
  script:
    - npm run test
  artifacts:
    paths:
      - Lab_Assistant/lambda/custom/test-report.xml
    reports:
      junit: Lab_Assistant/lambda/custom/test-report.xml

deploy:
  stage: deploy
  script:
    - npm run build
    - npm install -g ask-cli
    - ./ci-scripts/create-ask-aws-configs.js
      --ask-access-token ${ASK_ACCESS_TOKEN}
      --ask-refresh-token ${ASK_REFRESH_TOKEN}
      --ask-vendor-id ${ASK_VENDOR_ID}
      --aws-access-key-id ${AWS_ACCESS_KEY_ID}
      --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY}
    - npm run deploy
  only:
    - deploy@nfriend/lab-assistant
  except:
    variables:
      - $LAB_ASSISTANT

demo:
  stage: demo
  script:
    - echo "This job was triggered by Lab Assistant with the following environment variables:"
    - env | grep "LAB_ASSISTANT"
  only:
    variables:
      - $LAB_ASSISTANT
